lavalink:
    plugins:
    -   dependency: dev.lavalink.youtube:youtube-plugin:1.18.0
        snapshot: false
    -   dependency: com.github.topi314.lavasrc:lavasrc-plugin:4.8.1
        snapshot: false
    server:
        bufferDurationMs: 400
        filters:
            channelMix: true
            distortion: true
            equalizer: true
            karaoke: true
            lowPass: true
            rotation: true
            timescale: true
            tremolo: true
            vibrato: true
            volume: true
        frameBufferDurationMs: 5000
        gc-warnings: true
        nonAllocatingFrameBuffer: false
        opusEncodingQuality: 10
        password: "${LAVALINK_SERVER_PASSWORD:youshallnotpass}"
        playerUpdateInterval: 5
        resamplingQuality: LOW
        soundcloudSearchEnabled: true
        sources:
            bandcamp: true
            http: true
            local: false
            nico: true
            soundcloud: true
            twitch: true
            vimeo: true
            youtube: false
        trackStuckThresholdMs: 10000
        useSeekGhosting: true
        youtubePlaylistLoadLimit: 6
        youtubeSearchEnabled: true

logging:
    file:
        path: ./logs/
    level:
        lavalink: INFO
        root: INFO
    logback:
        rollingpolicy:
            max-file-size: 1GB
            max-history: 30
    request:
        enabled: true
        includeClientInfo: true
        includeHeaders: false
        includePayload: true
        includeQueryString: true
        maxPayloadLength: 10000

metrics:
    prometheus:
        enabled: false
        endpoint: /metrics

plugins:
    lavasrc:
        applemusic:
            albumLoadLimit: 6
            countryCode: US
            keyID: "${APPLE_MUSIC_KEY_ID:your key id}"
            mediaAPIToken: "${APPLE_MUSIC_API_TOKEN:your apple music api token}"
            musicKitKey: "${APPLE_MUSIC_KIT_KEY:}"
            playlistLoadLimit: 6
            teamID: "${APPLE_MUSIC_TEAM_ID:your team id}"
        deezer:
            formats:
            - FLAC
            - MP3_320
            - MP3_256
            - MP3_128
            - MP3_64
            - AAC_64
            masterDecryptionKey: "${DEEZER_MASTER_KEY:your master decryption key}"
        flowerytts:
            audioFormat: mp3
            silence: 0
            speed: 1.0
            translate: false
            voice: default voice
        lyrics-sources:
            deezer: false
            spotify: false
            vkmusic: false
            yandexmusic: true
            youtube: false
        providers:
        - ytsearch:"%ISRC%"
        - ytsearch:%QUERY%
        - ymsearch:%QUERY%
        sources:
            applemusic: false
            deezer: false
            flowerytts: false
            spotify: true
            vkmusic: false
            yandexmusic: true
            youtube: false
        spotify:
            albumLoadLimit: 6
            clientId: "${SPOTIFY_CLIENT_ID:}"
            clientSecret: "${SPOTIFY_CLIENT_SECRET:}"
            countryCode: US
            customTokenEndpoint: "${SPOTIFY_TOKENER_URL:http://spotify-tokener:49152/api/token}"
            localFiles: false
            playlistLoadLimit: 6
            preferAnonymousToken: false
            resolveArtistsInSearch: true
        yandexmusic:
            accessToken: "${YANDEX_MUSIC_TOKEN:}"
            albumLoadLimit: 1
            artistLoadLimit: 1
            playlistLoadLimit: 1
        youtube:
            countryCode: US
    youtube:
        allowDirectPlaylistIds: true
        allowDirectVideoIds: true
        allowSearch: true
        clientOptions:
            WEBEMBEDDED:
                playlistLoading: false
                searching: false
        clients:
        - TV
        - MUSIC
        - WEB
        - ANDROID_VR
        - ANDROID_MUSIC
        - WEBEMBEDDED
        - TVHTML5_SIMPLY
        enabled: true
        oauth:
            enabled: true
            refreshToken: "${YOUTUBE_OAUTH_TOKEN:}"

sentry:
    dsn: "${SENTRY_DSN:}"
    environment: "${SENTRY_ENV:production}"

server:
    address: 0.0.0.0
    http2:
        enabled: true
    password: "${LAVALINK_SERVER_PASSWORD:youshallnotpass}"
    port: ${SERVER_PORT:2333}
